services:
  tileserver-gl:
    image: rilusmahmud/tileserver-gl:beta-0.1.0
    container_name: tileserver-gl
    restart: always
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/data
    command:
      - "-l"
      - "output.log"
    deploy:
      resources:
        limits:
          memory: 8G 