services:
  tileserver-gl:
    image: rilusmahmud/tileserver-gl:main-1.0.0
    # image: tileserver-gl:local
    container_name: tileserver-gl
    restart: always
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/data
    deploy:
      resources:
        limits:
          memory: 8G 